version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - run:
          name: Build
          command: npm i && npm run build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --project brokerpro --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
